appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: IgJmTdnm+zUWA/NkPdKj8uc8/su7bZZLmrdexyOSSalMJ4JMEBgmL4Jcw3du/s86cl5nbd6dmWjiE0r5TOnb3XGQLUoyX1VefkK5mhYqE2+FkIW7/GuIrLehiBz18nECevYA+/xTA9whiKMVS4VKbSDOnXOXwQXKWE2UH2EcqQ0rSkCOGGEvodMrpmklDXnjGqBHgkEBft2SNGje7fGRVUWLkpXehnnyPbzrj09HoGKdWK4Bb/TftPzvCs78j2erLXomAWbAgv1JhJUHWdije6L+6GWJgxLdikSMIDU1C6sxBy2bsJWNGSQLN43OiyNtehJNoHBsAU8boXpPOmZxzf3xYwjbnQbVZMTdtkMIsmfY47f4UGXJpg24qaKqWoQbffPakC1uJNdw4wbuSga6NplS8yKVcEwPeC3JBXbIPAOt4RaMjR6WDVdNWeLIkb1KRgAgFDL8JDtXhLFrWETmIFOX7usgrAgvP9Q1UAKeFPd8X5EgCPkJMzdTotAVqw5Ff6WYfJx30BliNyVEOjF9O0kg9K3zMnBTwRjeOIaANyt7sOuaTD/5qTvudOykvvxkShqPL4fde+P9g3YKKPqcGbzLXpV/Vl4rMkZeyqB1iCUj2wpoXSLjFw3asbdxdxMlRtdeMWUPOYXvlLoHh2pj8F2Rdyf4aB9j1DJGcMzZv3s=}
