travis:
  secure:
    BINSTAR_TOKEN: Y2nB0mQPlSPqjeWkuIAuvQyBYkvUtsnQTwNO+lr0haEN6JeOWbHHf1B+1EmHG8E0cVfwq3KCD3/1FRrMcWTaMGz9jmKRQNDRcx2Sd5AQDqgntWqdS5QwyCSBadqowWF12ou4aVBQ2P/iUFw7r6dAEkatUydhpT3oGZT85Ujnpajvm9xD7XZb7PCIRGWkhvqWGWmiuA8y+lm7xdoIyWPM7zQWBh7uUxk7REdtG6SwIUGjcJvgszb0+rLQLXTuz9e/fWzislafnBxVGotEcqfuHfqEKd3t+x+WSehXNVwMr7wD8KvfRnuJ/2s5W6vv0ceSV6H2R4vGiPRGb8sDE/303WLvCOMpTzIK95BTeTMVXFrYxn9lY2LUUaDcCohBdxvKFI1+mqobQ1T/KZtgZrbUcHg8k5Vb8ubUKrZKlBomg29II+URspF3H92N4veNrmBtmpbwUrkZ2tcpN/ZWJQJOHWUD1VuV33Eqli9diDTy7sjdfoaQna21xc4g2ac6kNjKvXNKbI8uaxoTNI8e8hakA6VJ3Mct+p3v5A7jwoCnm0Rb4a4jG6T4e0mB7NZGJEloxbrjFomVN/utcusfQ/qAu92NGmgayKizwz1YPTeHkuLMxqAvj8lJWcEndCmNaZu2x+/iGzJC8eeQQ3nJrSUiNBMklbL3cdolUmfQHpsK3xg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
