travis:
  secure:
    BINSTAR_TOKEN: jIN8aw5Efy3Tbq/WLvBbAQf3Z0KRX9OZ0sLbYIW/TPXm4cOqJudYF66EOGx0EwZD8JycmnkSoxiIelTc3Mk2Q0fGp7NfwzBWdjTgjRieOXPqw9dMApljSBtZrphZd2GWHtsl+hwhsHT6p4WITnt6vpsUVuAoELudEP3id28pfP53MwvPHPYK6RePQXFXrBQ5qHXhmtIlVo/c7R/IRoDveQQmnlFaI+EBUG5kwiuO6uqBbhuKpGfZB1sg3rhxS1oju1vIMwQ7ju/AbRUDmNr1PKAvNVZujSmijQUw8JYtUwJDIT94sYljWqcwe8s1DfS3Qz3uklhK2SrGkLl1qJXCYr+xMr7BptzYa/cqCeISVG02idfNM6yQvzpzDULrOybogzZoe9MTplC+0RsALPJVyPzcA3ZaxXp2J7paQqzeMJjIBg6b+2PMLH1SiknTQZ6WvzzIGcoEfSVaazSbf7FDR6EoWD5VJ4uj7ab+nN+bpZ6t23oQ5ln/bCvM9ne0asrNbhFMMEw57mQuM+CT+4AWGZYjybKaNVOT3zOuW3GkWaWdSWOWn4P8cln3pBc+0/LgYqQhMc0wCfzUYernhthMTJUbc5dfbZ1sEsS6d8yQR13BY05s5+6dw3wCLZ6fFoGut7Nf++O0KjlIlXK4TPe5pqmjB+8pbrHVhNDYvphzS4o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
