travis:
  secure:
    BINSTAR_TOKEN: jg9/aL3RkRqwOkoGZaCK4Q4XUyeZEsqLOJUltlyvV7RBktY4UFtlizJiJ0S6tznhZ2NBYTeBmBLGG1eaWm+6PJij8MDtShlMYC8RtFDFqiHpPd6eCN763jJ5kgxyeLf0GQBhFj6gqFlNUGewo0y0Gk4XLAmOALR52hbpUdXPROyKHBfQDCUGhdkWnseWpI1KBoKMFSpsBCSMJox/oDcl9ykt4P8DC6kUUEny/VLNB90vJLvnzX32DMkx+cI4PHeoebW2nweaLg1r4HhNDhvLLEGsuzLnLyw81ctFL1ni7v8CArKKH56kKX8xRdc02TtCGr9PYEmJLyGeaoNIGk0myEAtd1KX0m3PAPylm3BMzOs2tYNZ8ltkGoYAN73zHEJgl4Tpi8AutfNNSU4ej5JouGV+l9H6qfILybJsENTW5lDwhhfwcC2wvGPo+UlEMMDOM0oCUnpGGkr8KBzgg6WNJSULuoM/Up/xSif1MFkx8liLoRcCi0UnKKYdqGLVj548z41a2gYV8XHgLNv9gJ6aXtKxW8MvKIcR/Jee8TVH5WFCCSlU1Q04fkWNAfU1VRjs7te4UOHk9UPfznyGlRLh0I5FEcdQBPu7CLkhfbODBj6U1iL82qOWXFVQiKj8Nodb/bUlMKnb3yqU/OofNvCPvq++lAKpBVL3U56vJMTLtc4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
