travis:
  secure:
    BINSTAR_TOKEN: cnIt0CmmPp93p3ubEasxfsDbFYf946wY4Bqogec++PEOISKc+SwUMVIvTJVd3f9KwATAR1SAMTwZWA2sJ5kIn8Z8Le47ErbdIjYPGFRjMXtHFc9hrc7nMW5kc0qzdkyS+DmvT/2PNzffd3uGwqXFu3qDIPYodqTVfUKTt6NrnUVvvL16LDku3xNVisTk9rsoYF4wHKHa9Vc+AzARIMbo2Oxa9PwfuTrDmou7eBhLiaHuzlylrpaia7eAfZhlJ/M03xD/AdUXryRoYeyYCoz58WJxxJHK+7K5+Zlq+VDlKUD2NdHfL+tIjg41gY9GwFCQFb30KXy7y4bakMR5KDQCrNOVQpAITrKKnqSA/nrrG+0IvrkAHwLpiTFZdLJUVDQTHqj7MbJ6dZp3WpFHtoi88UR23CqZFoLghXLstbVZy1dktBw/6O9cqPUrHbYkPMPCeePgAQhzwvWY53Cs/Iyh7XOTGLWK3uHYgd7BEimpSzQX94Bu3DTLxl+T9Ol1kSydByZMeZ1bs2H6uPk7ddmyPDzBVxMUH05AQHpL+9vyktzYaduSdf7MH63RuAtrCo0sfyh58yhdji/FwwO9pLWg5iNNvnY1nCg8Hu0dkguxr4Jl1inOHKQqmwQM/YE2gydTXbeMVIFUOW6ca4vxDgdOXDy0M5cEGwzejzszdCtLZVQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
